export {
  DocumentOperationType,
  type DocumentOperation,
  type DocumentOperationPayload,
  type CreateDocumentPayload,
  type UpdateTitlePayload,
  type UpdateContentPayload,
  type DeleteDocumentPayload,
  type CreateDocumentOperation,
  type UpdateTitleOperation,
  type UpdateContentOperation,
  type DeleteDocumentOperation,
  createDocumentOperation,
  createDocumentOperationWithId,
  createCreateDocumentOperation,
  createUpdateTitleOperation,
  createUpdateContentOperation,
  createDeleteDocumentOperation,
  isCreateDocumentOperation,
  isUpdateTitleOperation,
  isUpdateContentOperation,
  isDeleteDocumentOperation,
  documentOperationToVectorClock,
} from "./DocumentOperation.js";