import React from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

const authApiBaseUrl = import.meta.env.VITE_AUTH_API_BASE_URL ?? "http://localhost:3000";

export const LoginPage: React.FC = () => {
  const navigate = useNavigate(); const location = useLocation(); const { refreshUser } = useAuth();
  const [email, setEmail] = React.useState(""); const [password, setPassword] = React.useState(""); const [error, setError] = React.useState(""); const [busy, setBusy] = React.useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setBusy(true); try { const response = await fetch(`${authApiBaseUrl.replace(/\/$/, "")}/auth/login`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); if (response.status === 401) { setError("E-mail ou senha inválidos."); return; } if (!response.ok) { setError("Não foi possível entrar. Tente novamente."); return; } await refreshUser(); navigate((location.state as { from?: string } | null)?.from ?? "/app", { replace: true }); } catch { setError("Não foi possível entrar. Tente novamente."); } finally { setBusy(false); } };
  return <main className="min-h-screen flex items-center justify-center bg-[var(--background)] px-6"><form onSubmit={submit} className="w-full max-w-md rounded-2xl border-[var(--border)] bg-[var(--surface)] p-8 shadow-xl"><h1 className="text-2xl font-semibold mb-2">Entrar no Synclab</h1><p className="text-[var(--text-secondary)] mb-7">Acesse seu ambiente offline-first.</p>{error && <p role="alert" className="mb-4 text-[var(--error)]">{error}</p>}<label className="block text-sm mb-4">E-mail<input required type="email" value={email} onChange={e => setEmail(e.target.value)} className="mt-2 w-full rounded-lg border-[var(--border)] bg-[var(--surface-lowest)] p-3" /></label><label className="block text-sm mb-6">Senha<input required type="password" value={password} onChange={e => setPassword(e.target.value)} className="mt-2 w-full rounded-lg border-[var(--border)] bg-[var(--surface-lowest)] p-3" /></label><button disabled={busy} className="w-full rounded-lg bg-[var(--primary-container)] p-3 font-semibold text-white">{busy ? "Entrando..." : "Entrar"}</button><button type="button" onClick={() => window.open(`${authApiBaseUrl}/auth/google`, "_self")} className="mt-3 w-full rounded-lg border-[var(--border)] p-3 font-semibold">Continuar com Google</button><p className="mt-6 text-center text-sm text-[var(--text-secondary)]">Ainda não possui uma conta? <Link className="text-[var(--primary)]" to="/register">Criar conta</Link></p></form></main>;
};

